spring.application.name=demo_myapp

# DevTools: desactivar el reinicio automático (está causando: Unable to find the main class to restart)
spring.devtools.restart.enabled=false

# Serializar fechas (LocalDate) como string ISO ("yyyy-MM-dd") en las respuestas JSON
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

